apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://192.168.1.129:9411/api/v2/spans
  nameResolution:
    component: "consul"
    configuration:
      client:
        address: "192.168.1.102:8500"
      selfRegister: true

